# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rcqrs-rails}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ben Smith"]
  s.date = %q{2010-09-22}
  s.email = %q{ben@slashdotdash.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "example/event_storage.yml",
     "lib/generators/rcqrs/command/command_generator.rb",
     "lib/generators/rcqrs/command/templates/command.rb",
     "lib/generators/rcqrs/command/templates/handler.rb",
     "lib/generators/rcqrs/controller/controller_generator.rb",
     "lib/generators/rcqrs/controller/templates/controller.rb",
     "lib/generators/rcqrs/controller/templates/handler.rb",
     "lib/generators/rcqrs/event/event_generator.rb",
     "lib/generators/rcqrs/event/templates/event.rb",
     "lib/generators/rcqrs/event/templates/handler.rb",
     "lib/rcqrs-rails.rb",
     "lib/rcqrs/gateway.rb",
     "rcqrs-rails.gemspec"
  ]
  s.homepage = %q{http://github.com/slashdotdash/rcqrs-rails}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Rails 3 plugin to use the RCQRS library}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

